###

POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "krishna",
  "name": "Adam Richard",
  "password": "12345",
  "gender": "male",
  "location": "Detroit"
}
###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"krishna",
    "password": "12345"
}

###
PUT http://localhost:3000/change-password/
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}